#! /bin/sh

function ssh_auto_login() {

	echo $1
	echo $2
	echo $3

	ip_addr=$1
	user_name=$2
	password=$3
	
	expect -c "
	set timeout 30

	spawn ssh ${user_name}@${ip_addr}
	
	expect {
	\"(yes/no)?\" {send \"yes\n\"; exp_continue;}
	\"*assword:*\" {send \"${password}\n\"}
	}
	
	interact
	"

	return $?
}



ssh_auto_login $1 $2 $3
